config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  resources :courses, shallow: true do
    resources :chapters, shallow: true do
      resources :lessons, shallow: true do
        resources :questions do
          get :play, on: :collection
        end
      end
    end
  end


  root 'courses#index'

  resources :users, only: [:index] do
    post 'act_as', on: :member
    delete 'myself_again', on: :collection
  end

end

app/models/question.rb
class Question < ActiveRecord::Base

  include PermitsAttributes

  belongs_to :lesson, inverse_of: :questions
  has_one :answer, class_name: Proposal, foreign_key: :question_id, dependent: :destroy, inverse_of: :question

  validates :statement, presence: true
  validates :lesson, presence: true
  validates :answer, presence: true

  accepts_nested_attributes_for :answer, reject_if: lambda { |a| a[:statement].blank? }

end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :set_question, only: [:show, :edit, :update, :destroy]
  before_action :set_lesson, only: [:index, :new, :create, :play]

  # GET /questions
  # GET /questions.json
  def index
    @questions = @lesson.questions
  end

  # GET /questions/play
  def play
    @questions = @lesson.questions
  end

  # GET /questions/1
  # GET /questions/1.json
  def show
  end

  # GET /questions/new
  def new
    @question = @lesson.questions.build
    @question.build_answer
  end

  # GET /questions/1/edit
  def edit
  end

  # POST /questions
  # POST /questions.json
  def create
    @question = Question.new(question_params.merge(lesson: @lesson))

    respond_to do |format|
      if @question.save
        format.html { redirect_to lesson_questions_path(@lesson), notice: 'Question was successfully created.' }
        format.json { render :show, status: :created, location: @question }
      else
        format.html { render :new }
        format.json { render json: @question.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /questions/1
  # PATCH/PUT /questions/1.json
  def update
    respond_to do |format|
      if @question.update(question_params)
        format.html { redirect_to lesson_questions_path(@question.lesson), notice: 'Question was successfully updated.' }
        format.json { render :show, status: :ok, location: @question }
      else
        format.html { render :edit }
        format.json { render json: @question.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /questions/1
  # DELETE /questions/1.json
  def destroy
    @lesson = @question.lesson
    @question.destroy
    respond_to do |format|
      format.html { redirect_to @lesson, notice: 'Question was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
  def set_question
    @question = Question.find(params[:id])
  end

  def set_lesson
    @lesson = Lesson.find(params[:lesson_id])
  end

  def question_params
    Question.permits_params params.require(:question)
  end
end

app/views/questions/_form.html.erb
<%= simple_form_for([@lesson, @question]) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :statement %>

    <%= f.simple_fields_for :answer do |fa| %>
        <%= fa.input :statement %>
    <% end %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/questions/edit.html.erb
<div class="content-box col-centered">
  <h2>Editing Question</h2>

  <%= render 'form' %>

  <%= link_to 'Show', @question %> |
  <%= link_to 'Back', @question.lesson %>
</div>

app/views/questions/index.html.erb
<div class="content-box col-centered">
  <h2>
    <div class="btn-group pull-right">
      <%= link_to new_lesson_question_path(@lesson), class: 'btn btn-primary btn-xs' do %>
          <span class="glyphicon glyphicon-plus"></span> New Question
      <% end %>
    </div>
    Questions: <%= @lesson.title %>
  </h2>

  <table class="table">
    <thead>
    <tr>
      <th>Question</th>
      <th>Answer</th>
      <th></th>
    </tr>
    </thead>

    <tbody>
    <% @questions.each do |question| %>
        <tr>
          <td><%= question.statement %></td>
          <td><%= question.answer.statement %></td>
          <td>
            <%= actions_group show_btn(question),
                              edit_btn(edit_question_path(question)),
                              delete_btn(question) %>
          </td>
        </tr>
    <% end %>
    </tbody>
  </table>

  <%= link_to 'Back', @lesson %>
</div>

app/views/questions/new.html.erb
<div class="content-box col-centered">
  <h2>New Question</h2>

  <%= render 'form' %>

  <%= link_to 'Back', @lesson %>
</div>

app/views/questions/play.html.erb
<div class="content-box col-centered survey-container">
  <h2>
    <div class="btn-group pull-right">
      <%= link_to lesson_path(@lesson), class: 'btn btn-danger btn-xs' do %>
          <span class="glyphicon glyphicon-stop"></span> Stop
      <% end %>
    </div>
    Questions: <%= @lesson.title %>
  </h2>

  <% card_index = 0 %>
  <% @questions.each do |question| %>
      <% card_index += 1 %>
      <div class="survey-card" id="card-<%= card_index %>" data-card="<%= card_index %>">
        <div class="question">
          <p><%= question.statement %></p>
        </div>

        <div class="answer">
          <p><%= question.answer.statement %></p>
          <button class="btn btn-success">
            <span class="glyphicon glyphicon-play"></span> Next
          </button>
        </div>
      </div>
  <% end %>

  <div class="survey-card" id="card-end">
    <div>
      <%= link_to lesson_path(@lesson), class: 'btn btn-danger' do %>
          <span class="glyphicon glyphicon-stop"></span> Stop
      <% end %>
    </div>
  </div>
</div>

app/views/questions/show.html.erb
<div class="content-box col-centered">
  <h2>Question</h2>

  <p><%= @question.statement %></p>
  <p><%= @question.answer.statement %></p>

  <%= link_to 'Edit', edit_question_path(@question) %> |
  <%= link_to 'Back', @question.lesson %>
</div>