config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  resources :courses, shallow: true do
    resources :chapters, shallow: true do
      resources :lessons, shallow: true do
        resources :questions do
          get :play, on: :collection
        end
      end
    end
  end


  root 'courses#index'

  resources :users, only: [:index] do
    post 'act_as', on: :member
    delete 'myself_again', on: :collection
  end

end

app/models/user.rb
class User < ActiveRecord::Base

  rolify

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  include PermitsAttributes

  has_many :courses, inverse_of: :user, dependent: :destroy

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  # GET /users
  # GET /users.json
  def index
    @users = User.where.not(id: current_user.id)
  end

  # POST /users/1/act_as
  def act_as
    change_to_id = params[:id]
    admin_id = current_user.id.to_s
    session[:act_as] = {'user' => change_to_id, 'admin' => admin_id}
    sign_in_as_user change_to_id
    redirect_to :root, notice: 'Identity changed'
  end

  # DELETE /users/myself_again
  def myself_again
    sign_in_as_user session[:act_as]['admin']
    session.delete(:act_as)
    redirect_to :root, notice: 'Yourself again'
  end

  private
  def sign_in_as_user(user_id)
    sign_user = User.find(user_id)
    sign_in(:user, sign_user, {bypass: true})
  end
end

app/views/users/index.html.erb
<div class="content-box col-centered">
  <h2>Users</h2>

  <table class="table tablesorter">
    <thead>
    <tr>
      <th>ID</th>
      <th>Email</th>
      <th></th>
    </tr>
    </thead>

    <tbody>
    <% @users.each do |user| %>
        <tr>
          <td><%= user.id %></td>
          <td><%= user.email %></td>
          <td>
            <% if user.has_role?(:admin) %>
                <span class="green">ADMIN</span><br/>
            <% end %>
            <%= link_to 'Act as', act_as_user_path(user), method: :post, class: 'btn btn-primary' %>
          </td>
        </tr>
    <% end %>
    </tbody>
  </table>

</div>