config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  resources :courses, shallow: true do
    resources :chapters, shallow: true do
      resources :lessons, shallow: true do
        resources :questions do
          get :play, on: :collection
        end
      end
    end
  end


  root 'courses#index'

  resources :users, only: [:index] do
    post 'act_as', on: :member
    delete 'myself_again', on: :collection
  end

end

app/models/lesson.rb
class Lesson < ActiveRecord::Base

  include PermitsAttributes

  belongs_to :chapter, inverse_of: :lessons
  has_many :questions, inverse_of: :lesson, dependent: :destroy

  validates :title, presence: true
  validates :chapter, presence: true

end

app/controllers/lessons_controller.rb
class LessonsController < ApplicationController
  before_action :set_lesson, only: [:show, :edit, :update, :destroy]
  before_action :set_chapter, only: [:index, :new, :create]

  # GET /lessons
  # GET /lessons.json
  def index
    @lessons = @chapter.lessons
  end

  # GET /lessons/1
  # GET /lessons/1.json
  def show
  end

  # GET /lessons/new
  def new
    @lesson = @chapter.lessons.build
  end

  # GET /lessons/1/edit
  def edit
  end

  # POST /lessons
  # POST /lessons.json
  def create
    @lesson = Lesson.new(lesson_params.merge(chapter: @chapter))

    respond_to do |format|
      if @lesson.save
        format.html { redirect_to @lesson, notice: 'Lesson was successfully created.' }
        format.json { render :show, status: :created, location: @lesson }
      else
        format.html { render :new }
        format.json { render json: @lesson.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /lessons/1
  # PATCH/PUT /lessons/1.json
  def update
    respond_to do |format|
      if @lesson.update(lesson_params)
        format.html { redirect_to @lesson, notice: 'Lesson was successfully updated.' }
        format.json { render :show, status: :ok, location: @lesson }
      else
        format.html { render :edit }
        format.json { render json: @lesson.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /lessons/1
  # DELETE /lessons/1.json
  def destroy
    @chapter = @lesson.chapter
    @lesson.destroy
    respond_to do |format|
      format.html { redirect_to @chapter, notice: 'Lesson was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
  def set_lesson
    @lesson = Lesson.find(params[:id])
  end

  def set_chapter
    @chapter = Chapter.find(params[:chapter_id])
  end

  def lesson_params
    Lesson.permits_params params.require(:lesson)
  end
end

app/views/lessons/_form.html.erb
<%= simple_form_for([@chapter, @lesson]) do |f| %>
    <%= f.error_notification %>

    <div class="form-inputs">
      <%= f.input :title %>
      <%= f.input :content, input_html:{class: 'tinymce', rows: 20} %>
    </div>

    <div class="form-actions">
      <%= f.button :submit %>
    </div>
<% end %>
<%= tinymce %>

app/views/lessons/edit.html.erb
<div class="content-box col-centered">
  <h2>Editing Lesson</h2>

  <%= render 'form' %>

  <%= link_to 'Show', @lesson %> |
  <%= link_to 'Back', @lesson.chapter %>
</div>

app/views/lessons/index.html.erb
<div class="content-box col-centered">
  <h2>Lessons</h2>

  <table>
    <thead>
    <tr>
      <th>Title</th>
      <th colspan="3"></th>
    </tr>
    </thead>

    <tbody>
    <% @lessons.each do |lesson| %>
        <tr>
          <td><%= lesson.title %></td>
          <td><%= link_to 'Show', lesson %></td>
          <td><%= link_to 'Edit', edit_lesson_path(lesson) %></td>
          <td><%= link_to 'Destroy', lesson, method: :delete, data: {confirm: 'Are you sure?'} %></td>
        </tr>
    <% end %>
    </tbody>
  </table>

  <%= link_to 'New Lesson', new_chapter_lesson_path(@chapter) %>
</div>

app/views/lessons/new.html.erb
<div class="content-box col-centered">
  <h1>New Lesson</h1>

  <%= render 'form' %>

  <%= link_to 'Back', @chapter %>
</div>

app/views/lessons/show.html.erb
<div class="content-box col-centered">
  <h2>
    <div class="btn-group pull-right">
      <%= link_to play_lesson_questions_path(@lesson), class: 'btn btn-primary btn-xs' do %>
          <span class="glyphicon glyphicon-play"></span> Play
      <% end %>
      <%= link_to lesson_questions_path(@lesson), class: 'btn btn-default btn-xs' do %>
          <span class="glyphicon glyphicon-th-list"></span> Questions
      <% end %>
    </div>
    <%= @lesson.title %>
  </h2>

  <div><%= @lesson.content.html_safe %></div>

  <%= link_to 'Edit', edit_lesson_path(@lesson) %> |
  <%= link_to 'Back', @lesson.chapter %>
</div>