config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  resources :courses, shallow: true do
    resources :chapters, shallow: true do
      resources :lessons, shallow: true do
        resources :questions do
          get :play, on: :collection
        end
      end
    end
  end


  root 'courses#index'

  resources :users, only: [:index] do
    post 'act_as', on: :member
    delete 'myself_again', on: :collection
  end

end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  before_action :set_course, only: [:show, :edit, :update, :destroy]

  # GET /courses
  # GET /courses.json
  def index
    @courses = current_user.courses
  end

  # GET /courses/1
  # GET /courses/1.json
  def show
  end

  # GET /courses/new
  def new
    @course = Course.new
  end

  # GET /courses/1/edit
  def edit
  end

  # POST /courses
  # POST /courses.json
  def create
    @course = Course.new(course_params.merge(user: current_user))

    respond_to do |format|
      if @course.save
        format.html { redirect_to @course, notice: 'Course was successfully created.' }
        format.json { render :show, status: :created, location: @course }
      else
        format.html { render :new }
        format.json { render json: @course.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /courses/1
  # PATCH/PUT /courses/1.json
  def update
    respond_to do |format|
      if @course.update(course_params)
        format.html { redirect_to @course, notice: 'Course was successfully updated.' }
        format.json { render :show, status: :ok, location: @course }
      else
        format.html { render :edit }
        format.json { render json: @course.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /courses/1
  # DELETE /courses/1.json
  def destroy
    @course.destroy
    respond_to do |format|
      format.html { redirect_to courses_url, notice: 'Course was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
  def set_course
    @course = Course.find(params[:id])
  end

  def course_params
    Course.permits_params params.require(:course)
  end
end

app/views/courses/_form.html.erb
<%= simple_form_for(@course) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :title %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/courses/edit.html.erb
<div class="content-box col-centered">
  <h2>Editing Course</h2>

  <%= render 'form' %>

  <%= link_to 'Show', @course %> |
  <%= link_to 'Back', courses_path %>
</div>

app/views/courses/index.html.erb
<div class="content-box col-centered">
  <h2>
    <div class="btn-group pull-right">
      <%= link_to new_course_path, class: 'btn btn-primary btn-xs' do %>
          <span class="glyphicon glyphicon-plus"></span> New Course
      <% end %>
    </div>
    Courses
  </h2>

  <table class="table tablesorter">
    <thead>
    <tr>
      <th>Title</th>
      <th></th>
    </tr>
    </thead>

    <tbody>
    <% @courses.each do |course| %>
        <tr>
          <td><%= course.title %></td>
          <td>
            <%= actions_group show_btn(course),
                              edit_btn(edit_course_path(course)),
                              delete_btn(course) %>
          </td>
        </tr>
    <% end %>
    </tbody>
  </table>

</div>

app/views/courses/new.html.erb
<div class="content-box col-centered">
  <h2>New Course</h2>

  <%= render 'form' %>

  <%= link_to 'Back', courses_path %>
</div>

app/views/courses/show.html.erb
<div class="content-box col-centered">
  <h2>
    <div class="btn-group pull-right">
      <%= link_to new_course_chapter_path(@course), class: 'btn btn-primary btn-xs' do %>
          <span class="glyphicon glyphicon-plus"></span> New Chapter
      <% end %>
    </div>
    <%= @course.title %>
  </h2>

  <table class="table">
    <thead>
    <tr>
      <th>Title</th>
      <th></th>
    </tr>
    </thead>

    <tbody>
    <% @course.chapters.each do |chapter| %>
        <tr>
          <td><%= chapter.title %></td>
          <td>
            <%= actions_group show_btn(chapter),
                              edit_btn(edit_chapter_path(chapter)),
                              delete_btn(chapter) %>
          </td>
        </tr>
    <% end %>
    </tbody>
  </table>


  <%= link_to 'Edit', edit_course_path(@course) %> |
  <%= link_to 'Back', courses_path %>
</div>